# Site Settings
title: "Melkamu Gishu"
description: "Senior Data Scientist & Statistician"
url: "https://melkyed.github.io" # Ensure this matches your repo name
minimal_mistakes_skin: default
search: true

# Build Settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
include:
  - _pages

# Math Support (Crucial for Data Science)
kramdown:
  math_engine: mathjax

# Author Sidebar (Visible on every page)
author:
  name: "Melkamu Gishu"
  avatar: "/assets/images/profile.jpg" # Make sure to add a photo here later
  bio: "Data Scientist (MSc, BSc) specializing in advanced quantitative modeling, cloud migration, and Bayesian statistics."
  location: "Toronto, Canada"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/melkyed"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:melkyed@gmail.com"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true